<?php
?>
<h1><?=$this->heading?></h1>
<div>
    <?php
    if(isset($this->toolbar)){
        foreach($this->toolbar as $tool):
            if(isset($tool['button-dropdown'])){
                echo $this->partial('partial/common/button-dropdown', array('buttons' => $tool['button-dropdown']));
            }
            else{
                throw new \InvalidArgumentException("Uknown toolbar item");
            }
        endforeach;
    }?>
</div>
<table class="table table-bordered">
    <tbody>
<?php foreach($this->paginator as $entity):?>
    <tr>
    <?php 
    //@todo - this definitelly need some work to be done!
    $x = new \Zend\Stdlib\Hydrator\ClassMethods(false);
    $data = $x->extract($entity);
    
    foreach($this->columns as $column):?>
        <td>
        <?php
        if(is_string($column)) {
            echo $data[$column];
        }
        elseif(isset($column['button-dropdown'])) {
            echo $this->partial('partial/common/button-dropdown', array('buttons' => $column['button-dropdown'], 'params' => array('entity' => $entity, 'paginator' => $this->paginator)));
        }
        elseif(isset($column['render'])) {
            $render = $column['render'];
            if(is_string($render)) {
                echo $data[$render];
            }
            else if(is_callable($render)) {
                echo $render($entity, $this);
            }
        }
        else{
            throw new \InvalidArgumentException("Unknown columns item");
        }
        ?>
        </td>
    <?php endforeach?>
    </tr>
<?php endforeach?>
    </tbody>
</table>
<?=$this->paginationControl($this->paginator, 'Sliding', 'partial/common/pagination', (array)$this->paginationParams)?>