<?php
/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
$viewModel = $this->viewModel()->getCurrent();
$paginator = $viewModel->paginator;
$view = $this;
?>
<?=$this->partial('partial/entity/index.phtml', array(
    'heading' => $this->translate('Identities'),
    'paginator' => $paginator,
    'paginationParams' => array(
        'route' => 'identity/identity',
        'routeParams' => array('action' => 'index'),
    ),
    'columns' => array(
        array(
            'button-dropdown' => array(
                array(
                    'type' => 'update',
                    'url' => function($params) use ($view) {
                        return $view->url('identity/identity', array('action' => 'update', 'id' => $params['entity']->getId()));
                    }
                ),
                array(
                    'type' => 'remove',
                    'url' => function($params) use ($view) {
                        return $view->url('contact/contact', array('action' => 'remove', 'id' => $params['entity']->getId()));
                    }
                )
            )
        ),
        'displayName',
    )
));
                
