<?php
$viewModel = $this->viewModel()->getCurrent();
$paginator = $viewModel->paginator;
?>
<?=$this->partial('partial/entity/index.phtml', array(
    'heading' => $this->translate('Identities'),
    'paginator' => $paginator,
    'columns' => array(
        array(
            'urlActions' => array(
                'Edit' => function($entity, $view) {
                    return $view->url('identity/identity', array('action' => 'update', 'id' => $entity->getId()));
                },
            )
        ),
        'displayName',
    )
));
                