<?php
$viewModel = $this->viewModel()->getCurrent();
$paginator = $viewModel->paginator;
$view = $this;
?>
<?=$this->partial('partial/entity/index.phtml', array(
    'heading' => $this->translate('Identities'),
    'paginator' => $paginator,
    'columns' => array(
        array(
            'button-dropdown' => array(
                array(
                    'type' => 'update',
                    'url' => function($params) use ($view) {
                        return $view->url('identity/identity', array('action' => 'update', 'id' => $params['entity']->getId()));
                    }
                )
            )
        ),
        'displayName',
    )
));
                
