<?php
/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
?>
<ul class="breadcrumb">
    <?php
    foreach ($this->pages as $key => $page):
        ?>
        <li>
            <?php if ($key < count($this->pages)): ?>
                <a href="<?php echo $page->getHref(); ?>">
                <?php echo $page->getLabel(); ?></a>
                <?php if ($key < count($this->pages) - 1): ?>
                <span class="divider">/</span>
                <?php endif; ?>
            <?php else: ?>
                <?php echo $page->getLabel(); ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>