<?php

/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
?>

  <ul class="breadcrumb">
     <?php
     // iterate through the pages
     foreach ($this->pages as $key => $page):
         ?>
         <li>
             <?php
             // if this isn't the last page, add a link and the separator
             if ($key < count($this->pages) - 1):
                 ?>
                 <a href="<?=$page->getHref(); ?>"><?=$page->getLabel(); ?></a>
                 <span class="divider">/</span>
             <?php
             // otherwise, just output the name
             else:
             ?>
                <li class="active">
                    <?=$page->getLabel(); ?>
                </li>
             <?php endif; ?>
         </li>
         <?php endforeach; ?>
 </ul>