<?php
/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
$sanitazedButtons = array();
$defaultParams = array(
    'icon' => null,
    'url' => '#',
    'params' => array()
);

$params = (array)$this->params;

foreach($this->buttons as $button) {
    if(is_callable($button)) {
        $button = call_user_func($button, $params);
    }
    
    if(!empty($button['type'])) {
        switch($button['type']) {
            case 'update':
                $defaultParams['label'] = $this->translate('Update');
                $defaultParams['icon'] = 'icon-pencil';
                break;
            case 'remove':
                $defaultParams['label'] = $this->translate('Remove');
                $defaultParams['icon'] = 'icon-pencil';
                break;
            case 'create':
                $defaultParams['label'] = $this->translate('Create');
                break;
            default:
                throw new \InvalidArgumentException("Button 'type' attr '{$button['type']}' unknown");
        }
    }
    
    $button = array_merge($defaultParams, $button);
    
    if(empty($button['label'])) {
        throw new \InvalidArgumentException("Button 'label' attr has to be specified");
    }
    $button['params'] = array_merge($params, $button['params']);
    $sanitazedButtons[] = $button;
}

$priButton = array_shift($sanitazedButtons);
?>
<div class="btn-group">
    <a class="btn" href="<?=(is_callable($button['url']) ? call_user_func($button['url'], $button['params']) : $button['url'])?>"><?php if($button['icon']):?><i class="<?=$button['icon']?>"></i><?php endif?> <?=$priButton['label']?></a>
    <?php if($sanitazedButtons):?>
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
    <ul class="dropdown-menu">
        <?php foreach($sanitazedButtons as $button): ?>
            <li><a class="btn" href="<?=(is_callable($button['url']) ? call_user_func($button['url'], $button['params']) : $button['url'])?>"><?php if($button['icon']):?><i class="<?=$button['icon']?>"></i><?php endif?> <?=$button['label']?></a></li>
        <?php endforeach;?>
    </ul>
    <?php endif?>
</div>