<?php
/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
$page = $this->page;
$level = empty($this->level) ? 0 : $this->level;

$hasChildren = $page->hasPages();
if (!$hasChildren):?>
    <li><a href="<?=$page->getHref()?>"><?=$page->getLabel()?></a></li>
<?php else:
    $liClass = ($level > 0) ? 'dropdown-submenu' : 'dropdown';
    ?>
    <li class="<?=$liClass?>">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <?=$page->getLabel()?>
            <?php if($level === 0):?><b class="caret"></b><?php endif?>
        </a>
        <?php foreach ($page->getPages() as $child):
            if (!$this->navigation()->accept($child)) continue;
            ?> 
            <ul class="dropdown-menu">
                <?=$this->partial('partial/common/menu-item', array('page' => $child, 'level' => $level + 1))?>
            </ul>
        <?php endforeach ?>
    </li>
<?php endif ?>