<?php
/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
$params = $this->routeParams;
?>
<?php if ($this->pageCount): ?>
    <div class="pagination pagination-right">
        
        <!-- Previous page link -->
        
        <ul>
            <?php if (isset($this->previous)): ?>
                <li class="disabled">
                    <a href="<?php echo $this->url($this->route, array_merge($params, array('id' => $this->previous))); ?>">
                        &laquo</a>
                </li>
            <?php else: ?>
                <li class="active">
                    <span>&laquo</span>
                </li>
            <?php endif; ?>
                
            <!-- Numbered page links -->
            
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li class="disabled">
                        <a href="<?php echo $this->url($this->route, array_merge($params, array('id' => $page))); ?>">
                            <?php echo $page; ?></a> 
                    </li>
                <?php else: ?>
                    <li class="active">
                        <span><?php echo $page; ?></span>
                    </li>
            <?php endif; ?>
            <?php endforeach; ?>
                    
            <!-- Next page link -->

            <?php if (isset($this->next)): ?>
                <li class="disabled">
                    <a href="<?php echo $this->url($this->route, array_merge($params, array('id' => $this->next))); ?>">
                        &raquo;</a>
                </li>
            <?php else: ?>
                <li class="active">
                    <span>&raquo;</span>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>