
<?php
$viewModel = $this->viewModel()->getCurrent();
$paginator = $viewModel->paginator;

$this->headTitle('Identities');

//$identityData = array();
//foreach($paginator as $item) {
//    $identityData[] = $this->identity()->toArray($item);
//}
//$jsonData = \Zend\Json\Json::encode($identityData);
?>
<?=$this->partial('partial/entity/index.phtml', array(
    'heading' => $this->translate('Identities'),
    'paginator' => $paginator,
    'apiUrl' => $this->url('identity/api/identity', array(), array('base_relative' => true)),
    
));