<?php
$viewModel = $this->viewModel()->getCurrent();
$form = $viewModel->form;
$form->setName('identity-form');

//$form->setAttribute('data-ng-submit', 'xxx()');
$form->setAttribute('data-ng-controller' , 'IdentityUpdate');

$form->prepare();
?>
<h1><?=$this->translate('Identity')?></h1>
<div>
    <?=$this->partial('partial/form.phtml', array('form' => $form, 'modelPrefix' => 'identity'));?>
    <input type="submit" value="Submit" />
</div>