<?php
$viewModel = $this->viewModel()->getCurrent();
$form = $viewModel->form;
$form->setName('identity_form');
$form->setAttribute('action', null);

//$form->setAttribute('data-ng-submit', 'xxx()');
//$form->setAttribute('data-ng-controller' , 'IdentityUpdate');
$form->setAttribute('data-ng-controller', 'EntityUpdate');
$form->prepare();
?>
<div>
    <div class="container">
    <h1><?=$this->translate('Identity')?></h1>
    <?=$this->partial('partial/form/header.phtml', array('form' => $form));?>
    <?=$this->partial('partial/form/elements.phtml', array('form' => $form));?>
        <br>    
        <input class="btn btn-success" type="submit" value="Submit" ng-click="save(entity)"/>
    <?=$this->partial('partial/form/footer.phtml', array('form' => $form));?>
    </div>
</div>