    <?php
    $form = $this->form;
    ?>
<div class="control-group">
    <div class="controls">
        <?php
        foreach ($form->getIterator() as $element):
            if ($element instanceof Zend\Form\Element\Submit) {
                $element->setAttribute('class', $element->getAttribute('class') . ' btn btn-primary');
                echo $this->formElement($element);
            }
            if ($element instanceof Zend\Form\Element\Button){
                $element->setAttribute('class', $element->getAttribute('class') . ' btn');
                echo $this->formElement($element);
            }
         endforeach;
         ?>
    </div>
</div>    
