<?php
$form = $this->form;
$renderButtons = isset($this->renderButtons) ? $this->renderButtons : true;
?>
<?php
foreach($form->getIterator() as $element):
    if($element instanceof Zend\Form\FieldsetInterface) {
        echo $this->partial('partial/form/elements', array('form' => $element));
    }
    elseif(!$renderButtons && ($element instanceof \Zend\Form\Element\Submit || $element instanceof \Zend\Form\Element\Button)) {
        continue;
    }
    else {
        echo $this->partial('partial/form/row', array('form' => $form, 'element' => $element));
    }
endforeach;
?>