<?php
if($this->element instanceof \Zend\Form\Element\Hidden) {
    echo $this->formElement($this->element);
    return;
}
$this->element->setLabelAttributes(array(
    "class" => 'control-label'
));

$messages = $this->element->getMessages();
$hasErrors = !empty($messages);
$divClass = $hasErrors ? 'control-group error' : 'control-group';
?>
<div class="<?=$divClass?>">
    <?=$this->formLabel($this->element)?>
    <div class="controls">
        <?=$this->formElement($this->element)?>
        <?php if ($hasErrors):?>
            <span class="help-inline"><?=$this->formElementErrors($this->element)?></span>
        <?php endif?>
    </div>
</div>