<?php
$element = $this->element;

if($element instanceof \Zend\Form\Element\Hidden) {
    echo $this->formElement($element);
    return;
}
$element->setLabelAttributes(array(
    'class' => 'control-label'
));
$element->setAttributes(array(
    'data-toggle' => 'tooltip',
    'data-placement' => 'right',
));

$messages = $element->getMessages();
$hasErrors = !empty($messages);
$divClass = $hasErrors ? 'control-group error' : 'control-group';
?>
<div class="<?=$divClass?>">
    <?=$this->formLabel($element)?>
    <div class="controls">
        <?=$this->formElement($element)?>
        <?php if ($hasErrors):?>
            <span class="help-inline"><?=$this->formElementErrors($element)?></span>
        <?php endif?>
    </div>
</div>