<?php

/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
?>
<ul class="breadcrumb">
    <?=$this->navigation('DefaultNavigation')->breadcrumbs()
        ->setMinDepth(0)
        ->setRenderInvisible(true)//KapPage injects active page as invisible
    ?>
</ul>