<?php
/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
?>
<ul class="nav">
    <?php foreach ($this->container as $page):?>
         <?=$this->partial('partial/common/menu-item', array('page' => $page))?>
    <?php endforeach;?>
</ul>