<?php
/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */

use Zend\Mvc\Controller\Plugin\FlashMessenger;

$messenger = $this->flashMessenger()->getPluginFlashMessenger();
foreach(array(
        FlashMessenger::NAMESPACE_ERROR,
        FlashMessenger::NAMESPACE_SUCCESS,
        FlashMessenger::NAMESPACE_INFO,
        FlashMessenger::NAMESPACE_DEFAULT)
        as $namespace):
    
    $messenger->setNamespace($namespace);
    $currentMsgs = $messenger->getCurrentMessages();
    $messenger->clearCurrentMessages();
    $msgs = $messenger->getMessages();
    $userMsgs = array_merge($currentMsgs, $msgs);
    
    foreach($userMsgs as $msg):
        $msgText = $msg;
        if (is_array($msg)){
            $msgText = $msg['message'];    
        }
        ?>
        <div class="alert alert-<?=$namespace?>">
            <?=$msgText?>
        </div>
    <?php endforeach ?> 
<?php endforeach ?>

