<div class="container">
    <div class="span12">
        <h3>Good stuff!</h3>
        <h4>This is Kapitchi Showcase Application ...</h4>
        <p>So you know the application exists for these reasons:</p>
        <ul>
            <li>One big experiment with ZF2 development concepts focusing on extensibility - ultimate goal is to establish some concepts and best practices.</li>
            <li>We use this application for ZF2 module development and testing.</li>
            <li>It is working (sometime not) demonstration of all modules we have developed or used and to show how they can work together.</li>
        </ul>
        
        <h4>Modules</h4>
        <p>Following modules have been integrated or being developed:</p>
        <ul>
            <li>KapitchiIdentity - User management and authentication module supporting multiple user sessions.</li>
            <li>KapitchiContact - Contact manager</li>
            <li>KapitchiApp - Module (plugin) manager - install, enable, disable, update, un-install module related stuff. Note: we use concept of plugins at the moment but we realized later that plugin is essentially a 'smaller' ZF2 module primarily used to modify other modules - ZF2 module manager is being developed...</li>
            <li>... there are many more coming but we haven't developed twitter bootstrap interface for all of them yet.</li>
        </ul>
        <h4>Some interesting things to try</h4>
        <ul>
            <li>Try to enable/disable some plugins and check how it automatically affects related functionality</li>
            <li>... TODO ;)</li>
        </ul>
    </div>
</div>
