<?php
$options = array(
    'apiUrl' => $this->apiUrl,
);
?>
<div ng-controller="EntityIndex" ng-init="init(<?=$this->escapeHtmlAttr(\Zend\Json\Json::encode($options))?>)">
    <h1><?=$this->heading?></h1>
    <?php if($this->angular()->isAngularRequest()):?>
        <div class="gridStyle" ng-grid="gridOptions" style="width: 100%; height: 300px"></div>
    <?php else:?>
        <?php foreach($this->paginator as $item):?>
            <?=var_dump($item)?>
        <?php endforeach?>
    <?php endif; ?>
    
    <table border="1">
        <tr ng-repeat="entity in selectedEntities">
            <td>{{entity.id}}</td>
            <td>{{entity.displayName}}</td>
            <td>{{entity.contact.id}}</td>
        </tr>
    </table>
    
</div>
</div>