<?php
$form = $this->form;
$modelPrefix = empty($this->modelPrefix) ? 'formData' : $this->modelPrefix;
?>
<?php foreach($form->getIterator() as $element):
    
    //mz: this should be moved to checkbox view helper directly?
    if($element instanceof Zend\Form\Element\Checkbox) {
        $element->setAttribute('data-ng-true-value', '1');
        $element->setAttribute('data-ng-false-value', '0');
    }
    elseif($element instanceof Zend\Form\FieldsetInterface) {
        echo $this->partial('partial/form/elements.phtml', array('form' => $element, 'modelPrefix' => $modelPrefix . '.' . $element->getName()));
    }
    else {
        $elementName = $element->getName();
        $pos = strrpos($elementName, '[');
        if($pos !== false) {
            $elementName = substr($elementName, $pos + 1, -1);
        }
        
        $modelProp = $modelPrefix . '.' . $elementName;
        if($element instanceof \Zend\Form\Element\DateTime) {
            //$modelProp .= ' | date:"medium"';
        }
        $element->setAttribute('data-ng-model', $modelProp);
        
        echo $this->partial('partial/form/row.phtml', array('form' => $form, 'element' => $element));
    }
    ?>
<?php endforeach;?>