<?php

/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (c) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
?>
<div class="alert alert-info">
    Login using credential authentication method - we have created these users for you to use:
    <ul>
        <li>admin / xxx</li>
        <li>staff / xxx</li>
        <li>lender / xxx</li>
    </ul>
</div>