<br>
<br>
<br>
<?php 
$identity = $this->identity()->find(1);
$identityData = $this->identity()->toArray($identity);
?>
<div id="x" data-model="Identity" data-model-data="<?=$this->escapeHtmlAttr($this->json($identityData))?>">
    <input name="id" value="<?=$identity->getId()?>">
    <input name="created" value="<?=$identity->getCreated()->format('c')?>">
    <input name="authEnabled" value="<?=$identity->getAuthEnabled()?>">
    <input name="displayName" value="<?=$identity->getDisplayName()?>">
    <input name="ownerId" value="<?=$identity->getOwnerId()?>">
</div>

<table id="identities">
    <thead>
        
    </thead>
    <tbody>
        
    </tbody>
</table>

<button id="debugBtn">Debug</button>
<button id="saveBtn">Save</button>
        
<?php $this->inlineScript()->captureStart(); ?>
        $(function() {
            "use strict";
            var $el = $('#x');
            
            var Identity = Backbone.Model.extend({
                urlRoot: '/identity/api/backbone-dev/identity'
            });
            
            var data = $el.data('model-data');
            var identity = new Identity(data);
            
            var IdentityCollection = Backbone.Collection.extend({
                model: Identity,
                url: '/identity/api/backbone-dev/identity'
            });
            
            var idCol = new IdentityCollection();
            
            var view = new Backbone.View();
            view.setElement($('#identities'));
            var rowHtml = '<tr><td data-name="id"></td><td data-name="displayName"></td><td data-name="created"></td></tr>';
            var elManagerFactory = new Backbone.CollectionBinder.ElManagerFactory(rowHtml, "data-name");
            var collectionBinder = new Backbone.CollectionBinder(elManagerFactory);
            collectionBinder.bind(idCol, view.$('tbody'));
            
            idCol.fetch();
            
            //console.log(idCollection.toArray());
            //console.log(JSON.stringify(idCollection.toJSON()));
//            identity.on('change:color', function(model, color) {
//                $('.circle').css({background: color});
//            });

            /*var IdentityView = Backbone.View.extend({
                //tag: 'div',
                //template: _.template('<ul><% console.log(collection); _.each(collection.models, function(model) { %> <li><% print(model.get("changed")) %></li> <% }); %></ul>'),
                initialize: function(){ this.modelBinder = new Backbone.ModelBinder(); }, 
                render: function() {
                    this.modelBinder.bind(this.model, this.$el);
                    return this;
                }
            });
            
            var x = new IdentityView({
                model: identity
            });
            x.el = $el.get(0);
            x.$el = $el;
            x.render();*/
            
            $('#debugBtn').bind('click', function(e) {
                console.log(identity);
                console.log(identity.attributes);
            });
            $('#saveBtn').bind('click', function(e) {
                identity.save();
            });
              
        });
<?php $this->inlineScript()->captureEnd() ?>
