<?php
echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5);
?>
<html lang="en">
<head>
    <?=$this->render('layout/partial/head') ?>
</head>
<body>
    <?=$this->render('layout/partial/header')?>
    <div class="container">
        <?=$this->render('layout/partial/breadcrumbs')?>
        <?=$this->render('layout/partial/user-messages')?>
        <?=$this->content?>
    </div>
    <?= $this->plugin('InlineScript'); ?>
</body>
</html>
