<?php
echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5);
?>
<html lang="en">
<head>
    <?=$this->render('layout/partial/head') ?>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="#">Kapitchi Showcase</a>
                <div class="nav-collapse collapse">
                    <?=$this->navigation('DefaultNavigation')->menu()->setUlClass('nav')?>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <h1>Bootstrap starter template</h1>
        <p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>
    </div>
    <?= $this->plugin('InlineScript'); ?>
</body>
</html>
