<?php
//mz: XXX TODO hack to test angular

$this->headTitle('My site')->setSeparator(' / ');

if($this->angular()->isAngularRequest() && $this->exception) {
    echo $this->json(array(
        'title' => 'Exception',
        'exception' => array(
            'message' => $this->exception->getMessage(),
            'code' => $this->exception->getCode(),
            'traceString' => $this->exception->getTraceAsString(),
        ),
        //'content' => $this->content
    ));
    return;
}

//page action
if($this->angular()->isPageRequest()) {
    $headTitle = $this->plugin('HeadTitle')->renderTitle();
    echo $this->json(array(
        'title' => $headTitle,
        'content' => $this->content
    ));
    return;
}

//default angular action
if($this->angular()->isAngularRequest()) {
    echo $this->content;
    return;
}

$this->plugin('InlineScript')->appendFile($this->basePath('/assets/js/jquery.min.js'));
$this->plugin('InlineScript')->appendFile($this->basePath('/assets/js/bootstrap.js'));
$this->plugin('HeadLink')->appendStylesheet($this->basePath('/assets/css/bootstrap.css'));
$this->plugin('HeadLink')->appendStylesheet($this->basePath('/assets/css/bootstrap-responsive.css'));

$this->plugin('InlineScript')->appendFile($this->basePath('/assets/js/angular.js'));
$this->plugin('InlineScript')->appendFile($this->basePath('/assets/js/angular-resource.js'));
//$this->plugin('InlineScript')->appendFile('https://raw.github.com/angular/angular.js/master/src/ngLocale/angular-locale_en-gb.js');
$this->plugin('InlineScript')->appendFile($this->basePath('/assets/js/angular-locale_en-gb.js'));

//$this->plugin('InlineScript')->appendFile('https://raw.github.com/angular-ui/router/ui-states/build/angular-ui-states.js');
$this->plugin('InlineScript')->appendFile($this->basePath('/assets/js/angular-ui-states.js'));

//$this->plugin('InlineScript')->appendFile('http://angular-ui.github.com/bootstrap/ui-bootstrap-tpls-0.1.0.js');
$this->plugin('InlineScript')->appendFile($this->basePath('/assets/js/ui-bootstrap-tpls-0.1.0.js'));

//$this->plugin('InlineScript')->appendFile('https://raw.github.com/angular-ui/ng-grid/master/ng-grid-1.8.0.debug.js');
//$this->plugin('HeadLink')->appendStylesheet('https://raw.github.com/angular-ui/ng-grid/master/ng-grid.css');
//$this->plugin('InlineScript')->appendFile('http://angular-ui.github.com/ng-grid/lib/ng-grid.debug.js');
$this->plugin('InlineScript')->appendFile($this->basePath('/assets/js/ng-grid.debug.js'));
//$this->plugin('HeadLink')->appendStylesheet('http://angular-ui.github.com/ng-grid/css/ng-grid.css');
$this->plugin('HeadLink')->appendStylesheet($this->basePath('/assets/css/ng-grid.css'));

$this->plugin('InlineScript')->appendFile($this->basePath('/assets/js/KapApp.js'));
$this->plugin('HeadLink')->appendStylesheet($this->basePath('/assets/css/kap-angular-theme.css'));

echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5); ?>
<html lang="en" ng-app="KapApp">
  <head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <base href="<?=$this->basePath()?>/" />
    <?php
        //echo $this->plugin('HeadTitle');
        echo $this->plugin('HeadMeta');
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
    ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>
  <body>
      <div class="container-fluid">
      <div class="span2">
      <a  href="http://kapitchi.com/">
                    <img src="assets/img/kapitchi-logo.jpg" >
                </a>
      </div>
      
      <br>
      <div class="span10">  
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?=$this->url('home', array(), array('base_relative' => true))?>">Kapitchi ShowcaseApplication</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li ng-class="{ active: $state.includes('home') }"><a href="<?=$this->url('home', array(), array('base_relative' => true))?>">Home</a></li>
              <li ng-class="{ active: $state.includes('identity') }"><a href="<?=$this->url('identity/identity', array('action' => 'index'), array('base_relative' => true))?>">Identities</a></li>
              <li ng-class="{ active: $state.includes('contact') }"><a href="<?=$this->url('contact/contact', array('action' => 'index'), array('base_relative' => true))?>">Contacts</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
      </div>
      </div>
      <hr>
      
      <div class="container">
      <?php if(!$this->angular()->isAngularRequest() && $this->exception):?>
      <div><?=$this->content?></div>
      
      <?php else:?>
      <div ui-view></div>
      <?php endif?>
      
    <?php
        echo $this->plugin('InlineScript');
    ?>
      </div>
      
  </body>
  
</html>
