<?php
$viewModel = $this->viewModel()->getCurrent();
$form = $viewModel->form;

//@todo experimenting functionality
$method = $form->get('method');
$method->setAttribute('data-kap-control', 'switch');
$valueOptions = $method->getValueOptions();

//no authentication methods available? 
if(empty($valueOptions)):?>
    <div class="alert">
        No authentication method available!
    </div>
<?php return; endif;

foreach($valueOptions as $option) {
    $type = $option['value'];
    $fieldset = $form->get($type);
    
    $fieldset->setAttribute('data-kap-group', 'method');
    $fieldset->setAttribute('data-kap-value', $type);
}

?>
<?=$this->renderPre?>
<?=$this->partial('partial/form/default', array('form' => $form))?>
<?=$this->renderPost?>