<?php
$viewModel = $this->viewModel()->getCurrent();
$paginator = $viewModel->paginator;
$view = $this;
?>
<?=$this->partial('partial/entity/index', array(
    'heading' => $this->translate('Contacts'),
    'paginator' => $paginator,
    'paginationParams' => array(
        'route' => 'contact/contact',
        'routeParams' => array('action' => 'index'),
    ),
    'toolbar' => array(
        array(
            'button-dropdown' => array(
                function($params) use ($view) {
                    return array(
                    'type' => 'create',
                    'url' => $view->url('contact/contact', 
                            array('action' => 'create'))
                );
                }
            )
        )
    ),
    'columns' => array(
        array(
            'button-dropdown' => array(
                array(
                    'type' => 'update',
                    'url' => function($params) use ($view) {
                        return $view->url('contact/contact', array('action' => 'update', 'id' => $params['entity']->getId()));
                    }
                ),
                array(
                    'type' => 'remove',
                    'url' => function($params) use ($view) {
                        return $view->url('contact/contact', 
                                array('action' => 'remove', 'id' => $params['entity']->getId()),
                                array('query' => array('redirect_page' => $params['paginator']->getCurrentPageNumber())));
                    }
                )
            )
        ),
        'displayName',
    )
));

        
