<?php
$form = $this->form;

//@todo experimenting functionality
$typeHandle = $form->get('typeHandle');
$typeHandle->setAttribute('data-kap-control', 'switch');
$valueOptions = $typeHandle->getValueOptions();
foreach($valueOptions as $option) {
    $type = $option['value'];
    $fieldset = $form->get($type);
    $fieldset->setAttribute('data-kap-group', 'typeHandle');
    $fieldset->setAttribute('data-kap-value', $type);
}

?>
<?=$this->partial('partial/form/default', array('form' => $form));?>