<?php
/**
 * Kapitchi Zend Framework 2 Modules (http://kapitchi.com/)
 *
 * @copyright Copyright (coffee) 2012-2013 Kapitchi Open Source Team (http://kapitchi.com/open-source-team)
 * @license   http://opensource.org/licenses/LGPL-3.0 LGPL 3.0
 */
$viewModel = $this->viewModel()->getCurrent();
$paginator = $viewModel->deliveryPaginator;
$view = $this;
?>
<?=$this->partial('partial/entity/index.phtml', array(
    'heading' => $this->translate('Inbox'),
    'paginator' => $paginator,
    'paginationParams' => array(
        'route' => 'messenger/inbox',
        'routeParams' => array('action' => 'index'),
    ),
    'toolbar' => array(),
     'columns' => array(
        'id',
        array(
           'render' => function($entity, $view) {
                return $view->dateFormat(
                    $entity->getReceivedTime(),
                    IntlDateFormatter::MEDIUM, // date
                    IntlDateFormatter::MEDIUM // time
                );
           } 
        ),
        array(
           'render' => function($entity, $view) {
                return $view->message()
                    ->get($entity->getMessageId())->getSubject();
            } 
        ),
    )
));